# Generated by Django 5.0.7 on 2024-07-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
