# Generated by Django 5.0.7 on 2024-07-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuShop', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
