# Generated by Django 5.0.7 on 2024-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtakuShop', '0006_usuario_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
